---
ID: "9a055546-1702-4e0d-a104-61bb21d3508e"
Parent: "7294b298-b39c-435b-961e-765ea2e8525f"
Template: "7294b298-b39c-435b-961e-765ea2e8525f"
Path: /sitecore/templates/Feature/IACarousel/AI Generation Model Folder/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: "{14DAF934-CF9D-4A08-AA14-C9D989EC2F74}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240302T064621Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
